### ISSUE TITLE
New logo for Hisar

### ISSUE THREAD

**Issue by reallinfo** [NetCoreStack/Hisar#13]
I wanted to contribute to Hisar. I designed a logo for Hisar. If you like it, I'll send you the files.

![hisar](https://user-images.githubusercontent.com/36298335/37865664-7e5fe02c-2f88-11e8-92d7-bf1f66a84d11.jpg)

**Comment by gencebay** [comment]
Thank you for your interest and designing a logo but I thought something different like that
https://www.shutterstock.com/image-vector/building-castle-flat-icon-long-shadoweps10-244528312 
flatly and colored.

**Comment by reallinfo** [comment]
I designed a new logo.  How is that?  If you like it, you can make suggestions about colors.

![hisar](https://user-images.githubusercontent.com/36298335/37876211-e01d9b5a-3051-11e8-92c4-04f9f27cc0f9.jpg)

**Comment by canperk** [comment]
First comment has some asymmetric view, especially on the right side. Despite first comment, at the second comment I prefer straight and solid side wals instead of angled walls (for second logo with H letter)

**Comment by reallinfo** [comment]
Ah, yes. I made a mistake in the first comment. How is that?

![hisar2](https://user-images.githubusercontent.com/36298335/37965507-fb6745d2-31cd-11e8-9ff2-6e0c8ff7194a.jpg)

**Comment by canperk** [comment]
It looks like a charm :) @gencebay what do you think? :)

**Comment by gencebay** [comment]
Great! But I think we need to talk about the main colors.

**Comment by reallinfo** [comment]
Okey, If you decide on a color I will send the files. Good works.
